concepts: # Concept name and keywords to be recognised
  'hug': 
    - 'hug' 
    - 'squeeze'
    - 'bring it in'
  'highfive':
    - 'high five'
    - 'give me five'
    - 'up top'
  'dance':
    - 'dance'
    - 'show me your moves'
  'about':
    - 'tell me about yourself'
    - 'about yourself'
  'hello':
    - 'hello'
  'picture':
    - 'Take a picture'
    - 'Take a photo'
    - 'Take a selfie'
    - 'selfie'
applications: # Subset of concepts. Key: concept name, value: application ID
  'hug': 'hug'
  'highfive': 'highfive'
  'dance': 'arcadia/full_launcher'
  'picture': 'pose-photo/pose-photo-interactive'
precanned_text: # Subset of concepts. Intersection of applications and precanned_text has to be empty. 
# Otherwise, applications will shadow precanned_text. Key: concept name, value: list of possible answers. Randomly chosen at runtime.
  'about':
    - 'I am a service robot being trained to work at a supermarket in Finland. I would be happy to assist you with any questions you might have.'
  'hello':
    - 'Hello.'
